In [1]:
import pandas as pd
import numpy as np
import datetime

# Daily Data by Health Board

The following Github Repo https://github.com/DataScienceScotland/COVID-19-Management-Information contains information regarding scottish information which is pulled on a daily basis.

In [2]:
df_cases = pd.read_csv("https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Cumulative%20cases.csv")
df_hospital_confirmed = pd.read_csv("https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Hospital%20patients%20-%20Confirmed.csv")
df_hospital_all = pd.read_csv("https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Hospital%20patients.csv")
df_icu = pd.read_csv("https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20ICU%20patients.csv")

In [3]:
df_icu

,Date,Ayrshire and Arran,Borders,Dumfries and Galloway,Fife,Forth Valley,Grampian,Greater Glasgow and Clyde,Highland,Lanarkshire,Lothian,Orkney,Shetland,Tayside,Western Isles,The Golden Jubilee National Hospital
0,2020-03-18,*,*,*,*,*,*,*,*,*,5,*,*,*,*,*
1,2020-03-19,*,*,*,*,*,*,*,*,*,5,*,*,*,*,*
2,2020-03-20,*,*,*,*,*,*,*,*,*,6,*,*,*,*,*
3,2020-03-21,*,*,*,*,*,*,*,*,*,9,*,*,*,*,*
4,2020-03-22,*,*,*,*,*,*,*,*,*,7,*,*,*,*,*
5,2020-03-23,*,*,*,*,*,*,6,*,*,7,*,*,5,*,*
6,2020-03-24,*,*,*,*,*,*,8,*,5,14,*,*,6,*,*
7,2020-03-25,*,*,*,*,*,*,11,*,8,14,*,*,6,*,*
8,2020-03-26,*,*,*,*,*,*,12,*,11,12,*,*,5,*,*
9,2020-03-27,7,*,*,*,*,*,18,*,9,15,*,*,6,*,*
10,2020-03-28,7,*,*,5,*,*,24,*,11,17,*,*,7,*,*
11,2020-03-29,7,*,5,6,*,*,23,*,17,24,*,*,7,*,*
12,2020-03-30,9,*,*,6,*,*,22,*,18,29,*,*,9,*,*
13,2020-03-31,10,5,*,7,*,5,34,*,22,32,*,*,10,*,*
14,2020-04-01,11,6,*,10,*,*,36,5,26,33,*,*,10,*,*
15,2020-04-02,11,7,5,11,*,5,38,5,28,35,*,*,12,*,*
16,2020-04-03,14,7,6,12,*,5,45,5,28,36,*,*,14,*,*
17,2020-04-04,14,6,5,12,*,5,51,5,31,41,*,*,17,*,*
18,2020-04-05,14,8,5,10,*,6,54,5,31,46,*,*,13,*,*
19,2020-04-06,16,7,5,9,5,10,51,5,34,40,*,*,15,*,*
20,2020-04-07,14,7,5,11,7,11,54,6,30,41,*,*,11,*,*
21,2020-04-08,16,9,6,13,9,11,62,6,28,41,*,*,7,*,*
22,2020-04-09,15,7,9,13,7,13,64,6,31,39,*,*,7,*,*
23,2020-04-10,14,6,8,9,7,13,65,7,27,40,*,*,8,*,*
24,2020-04-11,15,6,7,10,7,13,69,7,30,36,*,*,8,*,*
25,2020-04-12,14,8,9,9,9,14,74,8,29,35,*,*,8,*,*
26,2020-04-13,14,8,8,6,7,12,74,6,30,36,*,*,8,*,*
27,2020-04-14,13,6,6,5,5,13,73,*,27,33,*,*,8,*,*
28,2020-04-15,13,6,6,5,7,15,71,5,29,28,*,*,6,*,*
29,2020-04-16,13,6,6,6,5,16,70,6,30,28,*,*,6,*,*
30,2020-04-17,11,6,5,6,6,15,67,6,29,30,*,*,5,*,*
31,2020-04-18,12,6,5,6,*,15,65,6,27,28,*,*,7,*,*
32,2020-04-19,10,6,5,5,*,13,62,6,27,29,*,*,6,*,*
33,2020-04-20,11,7,5,5,*,9,64,5,24,27,*,*,8,*,*
34,2020-04-21,10,9,5,6,*,10,60,5,22,29,*,*,7,*,*
35,2020-04-22,8,7,*,7,*,8,55,5,22,29,*,*,7,*,*
36,2020-04-23,10,*,*,6,5,12,49,*,19,27,*,*,6,*,*
37,2020-04-24,7,5,*,6,*,9,50,*,17,26,*,*,6,*,*
38,2020-04-25,7,5,*,6,6,9,49,*,18,25,*,*,5,*,*
39,2020-04-26,8,*,*,6,5,9,49,*,16,24,*,*,*,*,*
40,2020-04-27,7,*,*,6,6,9,47,*,17,24,*,*,*,*,*
41,2020-04-28,5,*,*,6,5,10,48,5,13,21,*,*,*,*,*
42,2020-04-29,6,*,*,6,6,10,42,*,12,17,*,*,*,*,*
43,2020-04-30,5,*,*,6,7,10,43,*,8,16,*,*,*,*,*
44,2020-05-01,6,*,*,6,6,13,44,*,8,16,*,*,*,*,*
45,2020-05-02,8,*,*,6,5,12,42,*,9,15,*,*,*,*,*
46,2020-05-03,8,*,*,6,*,13,39,*,8,12,*,*,*,*,*
47,2020-05-04,6,*,*,6,6,13,39,*,7,14,*,*,*,*,*
48,2020-05-05,8,*,*,5,*,13,32,*,10,18,*,*,*,*,*
49,2020-05-06,7,*,*,*,*,11,30,*,5,18,*,*,*,*,*
50,2020-05-07,7,*,*,*,*,11,32,*,7,12,*,*,*,*,*
51,2020-05-08,6,*,*,*,*,11,31,*,6,13,*,*,*,*,*
52,2020-05-09,9,*,*,*,*,10,30,*,8,20,*,*,*,*,*
53,2020-05-10,7,*,*,*,*,10,29,*,7,11,*,*,*,*,*

In [4]:
list(df_icu.columns.values)

['Date',
 'Ayrshire and Arran',
 'Borders',
 'Dumfries and Galloway',
 'Fife',
 'Forth Valley',
 'Grampian',
 'Greater Glasgow and Clyde',
 'Highland',
 'Lanarkshire',
 'Lothian',
 'Orkney',
 'Shetland',
 'Tayside',
 'Western Isles',
 'The Golden Jubilee National Hospital']

In [5]:
path_dict = {
                "cases" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Cumulative%20cases.csv",
                "hospital_covid" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Hospital%20patients%20-%20Confirmed.csv",
                "hospital_all" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20Hospital%20patients.csv",
                "icu" : "https://raw.githubusercontent.com/DataScienceScotland/COVID-19-Management-Information/master/COVID19%20-%20Daily%20Management%20Information%20-%20Scottish%20Health%20Boards%20-%20ICU%20patients.csv",
            }

In [6]:
def convert_date_to_week(date):
    date_list = date.split('-')
    date_num = list(map(int, date_list))
    a_date = datetime.date(date_num[0], date_num[1], date_num[2])
    week_number = a_date.isocalendar()[1]
    return week_number

In [7]:
def convert_date_to_day(date):
    date_list = date.split('-')
    date_num = list(map(int, date_list))
    a_date = datetime.date(date_num[0], date_num[1], date_num[2])
    day_of_year = (a_date - datetime.date(date_num[0], 1, 1)).days + 1
    return day_of_year

In [9]:
a = "2020-03-21"
convert_date_to_day(a)

81

In [25]:
def get_hbo_data(health_board, data_type):
    df = pd.read_csv(path_dict.get(data_type))
    df = df[['Date', health_board]]
    df['day_of_year'] = df['Date'].apply(lambda x : convert_date_to_day(x))
    df = df.set_index('day_of_year')
    df = df.drop(columns=['Date'])
    df = df.reset_index(inplace=False)
    return df

In [26]:
df_fife = get_hbo_data('Fife', 'hospital_all')

In [34]:
df_fife = df_fife.rename(columns={'day_of_year':'time', 'Fife':'valueA'})

In [35]:
df_fife.to_csv('fife_hospital_all2.csv')

In [38]:
df_fife

    time  valueA
0     78      18
1     79      24
2     80      20
3     81      16
4     82      23
5     83      28
6     84      42
7     85      28
8     86      45
9     87      51
10    88      50
11    89      64
12    90      81
13    91      74
14    92      60
15    93      98
16    94      95
17    95     115
18    96     120
19    97     115
20    98     131
21    99     127
22   100     136
23   101     131
24   102     129
25   103     122
26   104     121
27   105     120
28   106     105
29   107     125
30   108     124
31   109     119
32   110     127
33   111     120
34   112     138
35   113     135
36   114     141
37   115     136
38   116     133
39   117     153
40   118     152
41   119     146
42   120     148
43   121     142
44   122     139
45   123     130
46   124     123
47   125     125

In [50]:
df_fife['day_of_year'] = df_fife['Date'].apply(lambda x : convert_date_to_day(x))

In [53]:
df_fife

          Date  Fife  Date_new  day_of_year
0   2020-03-18    18        78           78
1   2020-03-19    24        79           79
2   2020-03-20    20        80           80
3   2020-03-21    16        81           81
4   2020-03-22    23        82           82
5   2020-03-23    28        83           83
6   2020-03-24    42        84           84
7   2020-03-25    28        85           85
8   2020-03-26    45        86           86
9   2020-03-27    51        87           87
10  2020-03-28    50        88           88
11  2020-03-29    64        89           89
12  2020-03-30    81        90           90
13  2020-03-31    74        91           91
14  2020-04-01    60        92           92
15  2020-04-02    98        93           93
16  2020-04-03    95        94           94
17  2020-04-04   115        95           95
18  2020-04-05   120        96           96
19  2020-04-06   115        97           97
20  2020-04-07   131        98           98
21  2020-04-08   127        99           99
22  2020-04-09   136       100          100
23  2020-04-10   131       101          101
24  2020-04-11   129       102          102
25  2020-04-12   122       103          103
26  2020-04-13   121       104          104
27  2020-04-14   120       105          105
28  2020-04-15   105       106          106
29  2020-04-16   125       107          107
30  2020-04-17   124       108          108
31  2020-04-18   119       109          109
32  2020-04-19   127       110          110
33  2020-04-20   120       111          111
34  2020-04-21   138       112          112
35  2020-04-22   135       113          113
36  2020-04-23   141       114          114
37  2020-04-24   136       115          115
38  2020-04-25   133       116          116
39  2020-04-26   153       117          117
40  2020-04-27   152       118          118
41  2020-04-28   146       119          119
42  2020-04-29   148       120          120
43  2020-04-30   142       121          121
44  2020-05-01   139       122          122
45  2020-05-02   130       123          123
46  2020-05-03   123       124          124
47  2020-05-04   125       125          125